from .InputDialog import InputDialog
from .NewShelfDialog import NewShelfDialog
from .EditAuthorDialog import EditAuthorDialog
from .SelectExistingCategoryDialog import SelectExistingCategoryDialog
from .SelectExistingAuthorDialog import SelectExistingAuthorDialog